[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#551A8B"
separator = ""

[icons]
name = "none"
[icons.overrides]
music_prev = "⇐"
music_play = "▶"
music_next = "⇒"

[[block]]
block = "net"
#device = "enp0s31f6"
device= "br0"
ip = true
speed_up = true
speed_down = true

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
on_collapsed_click = "spotify"
marquee = true
max_width = 40

[[block]]
block = "music"
player = "mps-yt"
buttons = ["prev", "play", "next"]
marquee = true
max_width = 40

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
command = "echo UPS: $(apcaccess -p BCHARGE -u)"
interval = 15

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
clickable = false
warning_mem = 70.0
critical_mem = 90.0

#[[block]]
#block = "sound"

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = false
show_temperature = false


[[block]]
block = "time"
interval = 60
format = "%y-%m-%d %H:%M"
